### PR TITLE
Sort viewlets on export

### PR DESCRIPTION
**Pull request by gforcada**
Fixes: https://github.com/plone/plone.app.viewletmanager/issues/7

### CODE REVIEW

**Comment by gforcada** [comment]
Sorry I mistakenly pushed that directly to master. I reverted it right away though.

**Comment by jensens** [comment]
Sorry, I dont get it, I try to to explain: 

1. We have here a viewlet manager which has some explicit order, i.e. ``logo, search, breadcrumbs``.
2. On import viewlets are created in this order. 
3. On export they got ordered alphabetically? So in XML the above example is ``breadcrumbs, logo,   search``.
4.  On import of the exported xml file the viewlet manager get configure with a order of ``breadcrumbs, logo,   search``. 

So IOW, after export-import cycle viewlets are in a different order?

What do I miss?

**Comment by davisagli** [comment]
It's sorting the managers so they are printed in a stable order in the xml; it's not doing anything to the order of viewlets within a manager.

**Comment by jensens** [comment]
omg, ok, sorry. so, why not pressing the green merge button then?

**Comment by gforcada** [comment]
Sorry for not wording it clear enough. I would have pressed the green button myself but as I had to change the tests I preferred to way for someone to give me an ack that the changes on the test are fine.

So anyway willing to put a :+1: on it? :)

**Comment by davisagli** [comment]
@gforcada please add a changelog entry on master

**Comment by gforcada** [comment]
Done on https://github.com/plone/plone.app.viewletmanager/commit/9aaea9f57d6702ced90a897c8f280dc45568b50d

**Pull request merged**
